- README.md
- package.json
- protoschool.md
- Migrate from npm to yarn
- Add README
- Remove Proto.md (this was moved to README)
CC @hugomrdias
> feat: migrate from npm to yarn

- examples/browser-ipns-publish/package.json
- lib/test-util-ipfs-example/package.json
`ipfs get` on the cli writes files/folders to disk, also tarballs
and gzipped tarballs. Also gzipped individual files.
In the API it's very similar to `ipfs.ls`. Make it more like the
cli so there's a clear reason to use one or the other.
Also adds types to `interface-ipfs-core` to better catch broken
types in `ipfs-core-types`.
BREAKING CHANGE: the output type of `ipfs.get` has changed and the `recursive` option has been removed from `ipfs.ls` since it was not supported everywhere
This PR was cherry pick from https://github.com/ipfs/js-ipfs/pull/3785
CC @hugomrdias
> chore: make ipfs get output tarballs

- examples/custom-ipfs-repo/package.json
- examples/custom-libp2p/package.json
- Adds missing dependencies
NOTE: It works when using workspaces because some package depends on the missing lib.
> fix: add missing dependencies

- .gitignore
- examples/browser-vue/.npmrc
The peer deps of `@vue/cli-plugin-*` cause npm7 to spin endlessly on install.
Use a `.npmrc` file to use the npm6 peer dep behaviour to fix this.
> chore: npm7 compat for browser-vue example

- examples/browser-angular/package.json
- examples/browser-ipns-publish/package.json
A couple of the examples were missing the `test-util-ipfs-example` dep.
> fix: add missing test-util-ipfs-example deps

- .github/workflows/ci.yml
- examples/browser-exchange-files/package.json
- examples/browser-ipns-publish/package.json
- examples/browser-ipns-publish/src/index.js
- examples/browser-vue/package.json
- yarn.lock
The current CI setup hoists all deps to the root which makes it
hard to spot when individual examples are missing dependencies.
This change switches up CI to run the tests for each example in
isolation so we should know when a dep is missing.
It also better reflects how js-ipfs tests the examples in CI.
> fix: test each example individually

- examples/browser-angular/package.json
This is depended on directly but isn't in the package.json
Annoyingly it works in CI by accident as the example also depends on `ipfs` which depends on `ipfs-core-types` as a dep.
> fix: add missing deps

- examples/browser-add-readable-stream/src/index.js
`ipfs.add` is for single items, `ipfs.addAll` is for multiple.
In the next ipfs release we will start enforcing this so update the example to call the correct method.
> chore: use ipfs.addAll for streams

- README.md
js-ipfs has switched to gh actions so update the section about adding new examples to reflect that.
> docs: update js-ipfs ci instructions

- examples/custom-ipfs-repo/index.js
- examples/custom-ipfs-repo/package.json
- yarn.lock
The `ipfs-core` dep was still `ipfs`
> fix: add missing dep

- examples/types-use-ipfs-from-typed-js/package.json
`ipfs-core-types` dep was missing.
> chore: add missing dep

- examples/browser-exchange-files/README.md
- examples/browser-exchange-files/package.json
- examples/browser-exchange-files/tests/test.js
The signalling server has been split out of the `libp2p-webrtc-star` module into it's own, so refactor the tests to use that and update the docs.
> chore: upgrade webrtc-star

- examples/browser-create-react-app/package.json
The `babel-plugin-transform-exponentiation-operator ` Babel plugin transforms `1n ** 1n` into `Math.pow(1n, 1n)` which doesn't work because `Math.pow` doesn't support BigInts - https://github.com/facebook/create-react-app/issues/6907#issuecomment-778178677
This is used in `@noble/ed25519` which recently got added to `libp2p-crypto` - https://github.com/libp2p/js-libp2p-crypto/pull/202
The fix is to change the `"browsersList"` setting to exclude ie and old android - https://github.com/blockstack/stacks.js/issues/1096#issuecomment-946350299
> fix: do not transform exponentiation operator

- examples/custom-ipld-formats/package.json
It pulls in the dag-json changes so the CIDs are different.
> fix: do not use ipfs-daemon@next

- examples/types-use-ipfs-from-ts/package.json
- examples/types-use-ipfs-from-ts/src/main.ts
If we import the CID type from ipfs-core we don't need the extra
multiformats dep.
> fix: simplify ts example

- examples/types-use-ipfs-from-ts/tsconfig.json
- examples/types-use-ipfs-from-typed-js/tsconfig.json
Seems necessary to get external tests passing with js-ipfs
> fix: add lib to tsconfig

- examples/types-use-ipfs-from-typed-js/package.json
- examples/types-use-ipfs-from-typed-js/src/main.js
All types needed for the example can be found in the `ipfs-core` package.
> fix: remove extra deps

- examples/browser-add-readable-stream/package.json
- examples/browser-exchange-files/package.json
- examples/browser-ipns-publish/package.json
- examples/browser-lit/package.json
- examples/browser-mfs/package.json
- examples/browser-parceljs/package.json
- examples/browser-readablestream/package.json
- examples/browser-script-tag/package.json
- examples/browser-sharing-node-across-tabs/package.json
- examples/browser-video-streaming/package.json
- examples/circuit-relaying/package.json
- examples/http-client-browser-pubsub/package.json
- examples/http-client-name-api/package.json
- examples/http-client-upload-file/package.json
- examples/ipfs-client-add-files/package.json
In CI parcel runs with `--no-autoinstall` so we need to explicitly depend on node polyfills.
> fix: add process and util dev deps to parcel projects

- examples/run-in-electron/package.json
The main module is called `main.js` not `main.cjs`. This prevents `npm start` from working.
> fix: fix electron main reference

- .github/workflows/ci.yml
- examples/browser-service-worker/tests/test.js
- examples/run-in-electron/package.json
- lib/test-util-ipfs-example/playwright/servers.js
testing to see if changes in #517 break CI workflows, or if they're already broken
---
They were broken. This PR fixes them and is blocking #517
> chore: fix CI workflows

- examples/browser-ipns-publish/package.json
- examples/browser-ipns-publish/tests/test.js
- examples/http-client-browser-pubsub/package.json
- examples/http-client-browser-pubsub/tests/test.js
- examples/http-client-name-api/package.json
- examples/http-client-name-api/tests/test.js
Tracking issue: https://github.com/ipfs/js-kubo-rpc-client/issues/37
Parent issue: https://github.com/ipfs/js-kubo-rpc-client/issues/6
Originating issue: https://github.com/ipfs/kubo/issues/9125
This PR is intended to update examples so that users will be pointed to `kubo-rpc-client` instead of `ipfs-http-client` when using Javascript/TypeScript to talk to Kubo.
fixes https://github.com/ipfs/js-kubo-rpc-client/issues/37
Things for reviewers to check:
1. Confirm I didn't miss any areas that should be updated (old mentions that should be updated that aren't yet)
2. Confirm the added information is accurate and desired
3. Confirm that the language used is aligned with maintainers' intentions
> feat: use kubo-rpc-client
